### ISSUE TITLE
-XX:+UseJVMCICompiler with OpenJDK 11.0.14 causes build warnings

### ISSUE THREAD

**Issue by Malax** [dwijnand/sbt-extras#344]
When using `sbt-extras` with OpenJDK `11.0.14`, the build log contains `java.lang.AssertionError`s related to the usage of JVMCI:

```
[info] welcome to sbt 1.4.1 (Azul Systems, Inc. Java 11.0.14)
Thread[JVMCI CompilerThread0,9,system]: Compilation of java.io.DataInputStream.readUTF(DataInput) failed: java.lang.AssertionError: dependencies invalid Code installation failed: dependencies invalid
Failed dependency of type leaf_type
  context = java.io.ByteArrayInputStream
  witness = sun.security.util.DerInputBuffer

	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:130)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:214)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.installMethod(CompilationTask.java:370)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:191)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:98)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:169)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:330)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:144)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:111)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:524)
To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
To print a message for a compilation failure without retrying the compilation, set CompilationFailureAction to Print (e.g., -Dgraal.CompilationFailureAction=Print).
Retrying compilation of java.io.DataInputStream.readUTF(DataInput)

[info] loading settings for project sbt-extras-11-0-14-debug-build from plugins.sbt ...
[info] loading project definition from /Users/manuel.fuchs/projects/sbt-extras-11.0.14-debug/project
Thread[JVMCI CompilerThread2,9,system]: Compilation of scala.collection.mutable.HashSet.index(int) failed: java.lang.AssertionError: dependencies invalid Code installation failed: dependencies invalid
Failed dependency of type abstract_with_unique_concrete_subtype
  context = *scala.collection.mutable.FlatHashTable
  class   = scala.collection.mutable.HashSet
  witness = *scala.collection.mutable.FlatHashTable

	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:130)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:214)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.installMethod(CompilationTask.java:370)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:191)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:98)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:169)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:330)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:144)
	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:111)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:524)
To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
To print a message for a compilation failure without retrying the compilation, set CompilationFailureAction to Print (e.g., -Dgraal.CompilationFailureAction=Print).
Retrying compilation of scala.collection.mutable.HashSet.index(int)

[info] loading settings for project sbt-extras-11-0-14-debug from build.sbt ...
[info] set current project to sbt-extras-11-0-14-debug (in build file:/Users/manuel.fuchs/projects/sbt-extras-11.0.14-debug/)
[info] Wrote /Users/manuel.fuchs/projects/sbt-extras-11.0.14-debug/migration/target/scala-2.13/aurinko-chatsync-migration_2.13-1.0-SNAPSHOT.pom
[info] Wrote /Users/manuel.fuchs/projects/sbt-extras-11.0.14-debug/core/target/scala-2.13/debug_2.13-1.0-SNAPSHOT.pom
[info] Wrote /Users/manuel.fuchs/projects/sbt-extras-11.0.14-debug/common/target/scala-2.13/common_2.13-1.0-SNAPSHOT.pom
[warn] You have no main class in your project. No start script will be generated.
[warn] You have no main class in your project. No start script will be generated.
[warn] You have no main class in your project. No start script will be generated.
[warn] You have no main class in your project. No start script will be generated.
[success] Total time: 1 s, completed 15 Feb 2022, 11:18:28
Graal diagnostic output saved in /Users/manuel.fuchs/projects/sbt-extras-11.0.14-debug/dumps/1644920299385/graal_diagnostics_84754.zip
```

I'm pretty sure `sbt-extras` isn't causing these build warning directly, but its usage of `-XX:+UseJVMCICompiler` at least triggers it, so I am reporting this here first. I'm unsure what the actual root cause is, I'm assuming a bug in OpenJDK `11.0.14` as it works just fine with `11.0.13`.

Would it make sense to work around this issue in `sbt-extras` by omitting `-XX:+UseJVMCICompiler` for OpenJDK `11.0.14`? It probably makes more sense to tackle the root issue instead. Making OpenJDK `11.0.14` a snowflake in `sbt-extras` does not seem great. Maybe someone has an idea how to debug this further so a root cause can be determined?

### OpenJDK

`java -version`:
```
openjdk version "11.0.14" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu11.54+23-CA (build 11.0.14+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.54+23-CA (build 11.0.14+9-LTS, mixed mode)
```

I tested this with other OpenJDK builds (Zulu, Heroku) on macOS and Linux, all have these warnings in the build log.

### sbt-extras
I used ef403f4, SHA256 hash of the file: 83336b1d0c92957cb57134282ec7c8095747f7021a815384ebb2da9750c25317

**Comment by dwijnand** [comment]
My guess is that 11.0.14 upgraded Graal version and that new Graal version has this issue.  I agree it doesn't make sense to special-case that version specifically.  So I'm unsure what to do, and I don't have time to dig deeper into it at the moment.

**Comment by Malax** [comment]
@dwijnand thanks for responding so quickly! No worries about not being able to dig deeper, I mainly wanted to bring this to broader attention. Thanks for putting your time into maintaining `sbt-extras`! :) 

Do you want to keep this issue open or close it out? I'm fine with either at this point. Considering this is very likely not `sbt-extras` related and a special case in `sbt-extras` for `11.0.14` doesn't make sense, closing out is probably the way to go.

**Comment by dwijnand** [comment]
Yeah, I guess you're right, we're unlikely to do something specifically in sbt-extras.  And if we do, we can always reopen.  Thanks for your kind words. ❤️

**Comment by hygt** [comment]
Hi @dwijnand this is still happening with recent OpenJDK 11 builds, 11.0.16 as we speak.

Is there a strong reason we want to keep the JVMCI compiler enabled? I assume people who truly want it for their sbt builds are using the GraalVM distributions anyway, not OpenJDK.

While this doesn't break builds, error logs get written in a `dumps` folder and that's a bit annoying.

**Comment by PenghaiZhang** [comment]
We also started seeing this warning after using OpenJDK 11. I am using Eclipse Adoptium Java 11.0.17.
